---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/home
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: content/custom-theme-example
  label: Custom theme example
  create: all
  match: "**/*"
- type: directory
  path: content/plugin-example
  label: Plugin example
  create: all
  match: "**/*"
- type: directory
  path: content/section-example
  label: Section example
  create: all
  match: "**/*"
- type: directory
  path: content/logo-example
  label: Logo example
  create: all
  match: "**/*"
- type: directory
  path: content/bundle-example
  label: Bundle example
  create: all
  match: "**/*"
- type: directory
  path: content/template-example
  label: Template example
  create: all
  match: "**/*"
upload_dir: "./static/uploads"
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.2
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.2
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.38.1
